-- ============================================
-- TravelGo Extended Data - Tours, Hotels, Restaurants
-- Thêm 40+ tours, 30+ hotels, 30+ restaurants với ảnh và giá
-- ============================================
USE travelgo;

-- ============================================
-- TOURS (40+ tours cho các điểm đến)
-- ============================================
INSERT INTO
  `Tour` (
    `id`,
    `name`,
    `slug`,
    `description`,
    `shortDescription`,
    `image`,
    `duration`,
    `price`,
    `originalPrice`,
    `rating`,
    `reviewCount`,
    `tags`,
    `featured`,
    `highlights`,
    `itinerary`,
    `destinationId`,
    `createdAt`,
    `updatedAt`
  )
VALUES
  -- Hạ Long
  (
    1,
    'Du thuyền Hạ Long 2N1Đ',
    'du-thuyen-ha-long-2n1d',
    'Tour du thuyền đưa bạn qua các hang động, làng chài và thưởng thức hải sản tươi ngon.',
    'Khám phá kỳ quan thiên nhiên thế giới trên du thuyền sang trọng.',
    '/uploads/avatars/ha-long4.jpg',
    2,
    3200000,
    3800000,
    4.7,
    126,
    '["Cruise", "Nature"]',
    1,
    '[{"icon":"ship","text":"Du thuyền 4 sao, phòng view vịnh"},{"icon":"fork-knife","text":"Hải sản tươi sống"},{"icon":"mountain","text":"Thăm hang Sửng Sốt, chèo kayak"}]',
    '[{"day":1,"title":"Check-in & tham quan hang động","activities":["Check-in","Ăn trưa trên tàu","Thăm hang","Câu mực đêm"]},{"day":2,"title":"Kayak & trả phòng","activities":["Kayak","Ăn trưa","Trả phòng"]}]',
    2,
    NOW(),
    NOW()
  ),
  (
    4,
    'Du thuyền Hạ Long 3N2Đ VIP',
    'du-thuyen-ha-long-3n2d-vip',
    'Du thuyền 5 sao với suite cao cấp, spa và hoạt động đa dạng.',
    'Trải nghiệm đẳng cấp trên vịnh Hạ Long.',
    '/uploads/avatars/ha-long4.jpg',
    3,
    5800000,
    6800000,
    4.9,
    89,
    '["Luxury", "Cruise"]',
    1,
    '[{"icon":"ship","text":"Suite 5 sao"},{"icon":"spa","text":"Spa & massage"},{"icon":"kayak","text":"Kayak & thể thao biển"}]',
    '[{"day":1,"title":"Check-in & welcome dinner","activities":["Check-in suite","Welcome cocktail","Dinner buffet"]},{"day":2,"title":"Khám phá hang động","activities":["Hang Sửng Sốt","Kayak Luồn Động","BBQ tối"]},{"day":3,"title":"Tai Chi & check-out","activities":["Tai Chi buổi sáng","Brunch","Check-out"]}]',
    2,
    NOW(),
    NOW()
  ),
  -- Hà Nội
  (
    2,
    'City Tour Hà Nội 1 ngày',
    'city-tour-ha-noi-1-ngay',
    'Trải nghiệm thủ đô nghìn năm với hướng dẫn viên địa phương.',
    'Thăm Văn Miếu, Lăng Bác, phố cổ và ẩm thực đường phố.',
    '/uploads/avatars/ha-noi.jpg',
    1,
    890000,
    NULL,
    4.6,
    88,
    '["City", "Culture"]',
    1,
    '[{"icon":"landmark","text":"Văn Miếu, Lăng Bác"},{"icon":"bowl-chopsticks","text":"Phở, bún chả"}]',
    '[{"day":1,"title":"City highlights","activities":["Văn Miếu","Lăng Bác","Phố cổ","Hồ Hoàn Kiếm"]}]',
    5,
    NOW(),
    NOW()
  ),
  (
    5,
    'Hà Nội Street Food Tour',
    'ha-noi-street-food-tour',
    'Khám phá ẩm thực đường phố Hà Nội cùng chuyên gia.',
    'Phở, bún chả, bánh mì, cà phê trứng và nhiều món khác.',
    '/uploads/avatars/ha-noi.jpg',
    1,
    650000,
    NULL,
    4.8,
    156,
    '["Food", "City"]',
    0,
    '[{"icon":"bowl","text":"10+ món ăn địa phương"},{"icon":"coffee","text":"Cà phê trứng nổi tiếng"}]',
    '[{"day":1,"title":"Food adventure","activities":["Phở buổi sáng","Bún chả trưa","Bánh mì chiều","Cà phê tối"]}]',
    5,
    NOW(),
    NOW()
  ),
  -- Phú Quốc
  (
    3,
    'Khám phá Phú Quốc 3N2Đ',
    'kham-pha-phu-quoc-3n2d',
    'Combo tham quan Nam đảo, VinWonders và VinSafari.',
    'Biển xanh, cát trắng, ngắm hoàng hôn và câu cá đêm.',
    '/uploads/avatars/phu-quoc.jpg',
    3,
    5200000,
    NULL,
    4.8,
    64,
    '["Beach", "Family"]',
    1,
    '[{"icon":"beach","text":"Sunset Sanato"},{"icon":"fish","text":"Câu cá đêm"}]',
    '[{"day":1,"title":"Nam đảo","activities":["Hòn Thơm","Cáp treo","Lặn ngắm san hô"]},{"day":2,"title":"VinWonders & VinSafari","activities":["Công viên chủ đề","Thế giới động vật"]},{"day":3,"title":"Tự do & mua sắm","activities":["Chợ đêm","Đặc sản"]}]',
    4,
    NOW(),
    NOW()
  ),
  (
    6,
    'Tour 4 đảo Phú Quốc',
    'tour-4-dao-phu-quoc',
    'Lặn biển, câu cá và BBQ trên đảo hoang.',
    'Khám phá 4 hòn đảo đẹp nhất Phú Quốc.',
    '/uploads/avatars/phu-quoc.jpg',
    1,
    980000,
    1200000,
    4.7,
    234,
    '["Island", "Snorkeling"]',
    0,
    '[{"icon":"island","text":"4 hòn đảo"},{"icon":"fish","text":"Câu cá & BBQ"}]',
    '[{"day":1,"title":"Island hopping","activities":["Hòn Mây Rút","Hòn Gầm Ghì","Hòn Móng Tay","BBQ trưa"]}]',
    4,
    NOW(),
    NOW()
  ),
  -- Đà Lạt
  (
    7,
    'Đà Lạt Classic 2N1Đ',
    'da-lat-classic-2n1d',
    'Thăm thác Datanla, Thiền viện Trúc Lâm, vườn hoa thành phố.',
    'Thành phố ngàn hoa với khí hậu mát mẻ.',
    '/uploads/avatars/da-lat.jpg',
    2,
    2800000,
    3200000,
    4.5,
    178,
    '["Nature", "Romantic"]',
    1,
    '[{"icon":"flower","text":"Vườn hoa nhiệt đới"},{"icon":"waterfall","text":"Thác Datanla"}]',
    '[{"day":1,"title":"Điểm tham quan chính","activities":["Thác Datanla","Thiền viện","Hồ Tuyền Lâm"]},{"day":2,"title":"Nông trại & cafe","activities":["Nông trại rau củ","Cafe view đẹp","Chợ Đà Lạt"]}]',
    3,
    NOW(),
    NOW()
  ),
  (
    8,
    'Đà Lạt Adventure 3N2Đ',
    'da-lat-adventure-3n2d',
    'Canyoning, trekking và khám phá núi rừng Đà Lạt.',
    'Phiêu lưu mạo hiểm trong thiên nhiên.',
    '/uploads/avatars/da-lat.jpg',
    3,
    4200000,
    NULL,
    4.8,
    92,
    '["Adventure", "Trekking"]',
    0,
    '[{"icon":"mountain","text":"Canyoning thác Datanla"},{"icon":"hiking","text":"Trekking Langbiang"}]',
    '[{"day":1,"title":"Canyoning","activities":["Huấn luyện","Canyoning thác","Nghỉ ngơi"]},{"day":2,"title":"Trekking Langbiang","activities":["Leo núi","Picnic trên đỉnh"]},{"day":3,"title":"Zipline & relax","activities":["Zipline","Cafe","Mua sắm"]}]',
    3,
    NOW(),
    NOW()
  ),
  -- Đà Nẵng
  (
    9,
    'Đà Nẵng - Hội An 3N2Đ',
    'da-nang-hoi-an-3n2d',
    'Khám phá Bà Nà Hills, phố cổ Hội An và bãi biển Mỹ Khê.',
    'Combo 2 thành phố miền Trung.',
    '/uploads/avatars/da-nang.png',
    3,
    4800000,
    5500000,
    4.7,
    145,
    '["City", "Beach"]',
    1,
    '[{"icon":"cable-car","text":"Bà Nà Hills"},{"icon":"lantern","text":"Phố cổ Hội An"}]',
    '[{"day":1,"title":"Đà Nẵng city tour","activities":["Ngũ Hành Sơn","Bãi biển Mỹ Khê","Cầu Rồng"]},{"day":2,"title":"Bà Nà Hills","activities":["Cáp treo","Cầu Vàng","Fantasy Park"]},{"day":3,"title":"Hội An","activities":["Phố cổ","Làm đèn lồng","Chợ đêm"]}]',
    6,
    NOW(),
    NOW()
  ),
  -- Sa Pa
  (
    10,
    'Sa Pa Trekking 3N2Đ',
    'sapa-trekking-3n2d',
    'Chinh phục Fansipan, trekking ruộng bậc thang và làng bản.',
    'Khám phá miền núi Tây Bắc.',
    '/uploads/avatars/sapa.jpg',
    3,
    3800000,
    4200000,
    4.6,
    167,
    '["Trekking", "Nature"]',
    1,
    '[{"icon":"mountain","text":"Fansipan - nóc nhà Đông Dương"},{"icon":"rice","text":"Ruộng bậc thang"}]',
    '[{"day":1,"title":"Sa Pa town","activities":["Check-in","Thị trấn Sa Pa","Chợ tình"]},{"day":2,"title":"Fansipan","activities":["Cáp treo","Đỉnh Fansipan","Chùa"]},{"day":3,"title":"Trekking","activities":["Trekking Cát Cát","Làng bản","Check-out"]}]',
    7,
    NOW(),
    NOW()
  ),
  (
    11,
    'Sa Pa Homestay 2N1Đ',
    'sapa-homestay-2n1d',
    'Trải nghiệm sống cùng người dân tộc, trekking và văn hóa.',
    'Homestay giữa ruộng bậc thang.',
    '/uploads/avatars/sapa.jpg',
    2,
    2200000,
    NULL,
    4.8,
    203,
    '["Homestay", "Culture"]',
    0,
    '[{"icon":"home","text":"Homestay người H''Mông"},{"icon":"hiking","text":"Trekking Tả Van"}]',
    '[{"day":1,"title":"Trekking & homestay","activities":["Trekking Tả Van","Homestay","Giao lưu văn hóa"]},{"day":2,"title":"Làng bản","activities":["Thăm làng","Mua thổ cẩm","Check-out"]}]',
    7,
    NOW(),
    NOW()
  ),
  -- Hội An
  (
    12,
    'Hội An Lantern Tour 1 ngày',
    'hoi-an-lantern-tour-1-ngay',
    'Khám phá phố cổ, làm đèn lồng và thả hoa đăng.',
    'Phố cổ thơ mộng với đèn lồng.',
    '/uploads/avatars/hoi-an.png',
    1,
    890000,
    NULL,
    4.7,
    189,
    '["Culture", "City"]',
    0,
    '[{"icon":"lantern","text":"Làm đèn lồng"},{"icon":"boat","text":"Thả hoa đăng"}]',
    '[{"day":1,"title":"Hội An highlights","activities":["Chùa Cầu","Làm đèn lồng","Phố cổ tối","Thả hoa đăng"]}]',
    8,
    NOW(),
    NOW()
  ),
  -- Nha Trang
  (
    13,
    'Nha Trang Beach 2N1Đ',
    'nha-trang-beach-2n1d',
    'Tắm biển, lặn ngắm san hô và tắm bùn khoáng.',
    'Thành phố biển sôi động.',
    '/uploads/avatars/nha-trang.jpg',
    2,
    3200000,
    3800000,
    4.6,
    156,
    '["Beach", "Relax"]',
    1,
    '[{"icon":"beach","text":"Bãi biển đẹp"},{"icon":"spa","text":"Tắm bùn khoáng"}]',
    '[{"day":1,"title":"Tham quan đảo","activities":["Đảo Hòn Mun","Lặn biển","Aquarium"]},{"day":2,"title":"Relax","activities":["Tắm bùn","Vinpearl","Shopping"]}]',
    12,
    NOW(),
    NOW()
  ),
  -- Ninh Bình
  (
    14,
    'Ninh Bình - Tràng An 2N1Đ',
    'ninh-binh-trang-an-2n1d',
    'Đi thuyền Tràng An, Tam Cốc và thăm Bái Đính.',
    'Non nước hữu tình Ninh Bình.',
    '/uploads/avatars/ninh-binh.jpg',
    2,
    2600000,
    3000000,
    4.7,
    134,
    '["Nature", "Boat"]',
    1,
    '[{"icon":"boat","text":"Đi thuyền Tràng An"},{"icon":"temple","text":"Chùa Bái Đính"}]',
    '[{"day":1,"title":"Tràng An","activities":["Đi thuyền","Hang động","Chùa Bái Đính"]},{"day":2,"title":"Tam Cốc","activities":["Đi thuyền Tam Cốc","Hang Múa","Check-out"]}]',
    1,
    NOW(),
    NOW()
  ),
  -- Huế
  (
    15,
    'Huế Heritage 2N1Đ',
    'hue-heritage-2n1d',
    'Thăm Đại Nội, lăng tẩm và thưởng thức ẩm thực cung đình.',
    'Cố đô Huế văn hóa UNESCO.',
    '/uploads/avatars/hue.jpg',
    2,
    2800000,
    NULL,
    4.5,
    112,
    '["Heritage", "Culture"]',
    0,
    '[{"icon":"palace","text":"Đại Nội Huế"},{"icon":"bowl","text":"Ẩm thực cung đình"}]',
    '[{"day":1,"title":"Di tích","activities":["Đại Nội","Lăng Khải Định","Chùa Thiên Mụ"]},{"day":2,"title":"Thưởng thức ẩm thực","activities":["Ẩm thực cung đình","Chợ Đông Ba","Perfume River"]}]',
    9,
    NOW(),
    NOW()
  ),
  -- Cần Thơ
  (
    16,
    'Cần Thơ - Chợ nổi 2N1Đ',
    'can-tho-cho-noi-2n1d',
    'Thăm chợ nổi Cái Răng, vườn trái cây và làng nghề.',
    'Miền Tây sông nước.',
    '/uploads/avatars/can-tho.jpg',
    2,
    2400000,
    NULL,
    4.6,
    98,
    '["Culture", "River"]',
    0,
    '[{"icon":"boat","text":"Chợ nổi Cái Răng"},{"icon":"fruit","text":"Vườn trái cây"}]',
    '[{"day":1,"title":"Chợ nổi","activities":["Chợ nổi Cái Răng","Vườn trái cây","Cồn Sơn"]},{"day":2,"title":"Làng nghề","activities":["Làng nghề","Ẩm thực miền Tây","Check-out"]}]',
    10,
    NOW(),
    NOW()
  ),
  -- Vũng Tàu
  (
    17,
    'Vũng Tàu Beach 2N1Đ',
    'vung-tau-beach-2n1d',
    'Tắm biển, thăm núi Tượng và thưởng thức hải sản.',
    'Biển gần Sài Gòn.',
    '/uploads/avatars/vung-tau.jpg',
    2,
    1800000,
    NULL,
    4.4,
    145,
    '["Beach", "Relax"]',
    0,
    '[{"icon":"beach","text":"Bãi Sau, Bãi Trước"},{"icon":"statue","text":"Núi Tượng Chúa"}]',
    '[{"day":1,"title":"Tham quan","activities":["Bãi Trước","Núi Tượng","Hải sản"]},{"day":2,"title":"Beach day","activities":["Bãi Sau","Relax","Check-out"]}]',
    11,
    NOW(),
    NOW()
  ),
  -- Quy Nhơn
  (
    18,
    'Quy Nhơn Relax 3N2Đ',
    'quy-nhon-relax-3n2d',
    'Nghỉ dưỡng bãi biển hoang sơ, thăm Eo Gió.',
    'Biển yên bình Quy Nhơn.',
    '/uploads/avatars/quynhon.jpg',
    3,
    3600000,
    NULL,
    4.7,
    87,
    '["Beach", "Nature"]',
    0,
    '[{"icon":"beach","text":"Bãi biển hoang sơ"},{"icon":"wind","text":"Eo Gió"}]',
    '[{"day":1,"title":"Arrival","activities":["Check-in resort","Bãi biển","Sunset"]},{"day":2,"title":"Eo Gió","activities":["Eo Gió","Kỳ Co","BBQ"]},{"day":3,"title":"Relax","activities":["Free time","Check-out"]}]',
    13,
    NOW(),
    NOW()
  ),
  -- Hà Giang
  (
    19,
    'Hà Giang Loop 4N3Đ',
    'ha-giang-loop-4n3d',
    'Chinh phục cung đường hạnh phúc, Đồng Văn và Lũng Cú.',
    'Cực Bắc Việt Nam.',
    '/uploads/avatars/hagiang-1.jpg',
    4,
    4800000,
    5500000,
    4.9,
    234,
    '["Motorbike", "Adventure"]',
    1,
    '[{"icon":"motorbike","text":"Cung đường hạnh phúc"},{"icon":"flag","text":"Cột cờ Lũng Cú"}]',
    '[{"day":1,"title":"Hà Giang - Quản Bạ","activities":["Quản Bạ","Cổng trời","Homestay"]},{"day":2,"title":"Yên Minh - Đồng Văn","activities":["Dinh Vua Mèo","Đồng Văn","Phố cổ"]},{"day":3,"title":"Mã Pì Lèng - Mèo Vạc","activities":["Mã Pì Lèng","Mèo Vạc"]},{"day":4,"title":"Return","activities":["Du Già","Hà Giang","Check-out"]}]',
    14,
    NOW(),
    NOW()
  ),
  -- Mù Cang Chải
  (
    20,
    'Mù Cang Chải mùa lúa chín 3N2Đ',
    'mu-cang-chai-mua-lua-chin-3n2d',
    'Ngắm ruộng bậc thang vàng óng mùa lúa chín.',
    'Ruộng bậc thang đẹp nhất Việt Nam.',
    '/uploads/avatars/mucangchai.jpg',
    3,
    3400000,
    NULL,
    4.8,
    76,
    '["Nature", "Photography"]',
    0,
    '[{"icon":"rice","text":"Ruộng bậc thang vàng"},{"icon":"camera","text":"Photography tour"}]',
    '[{"day":1,"title":"Hà Nội - Mù Cang Chải","activities":["Nghĩa Lộ","Tú Lệ","Check-in"]},{"day":2,"title":"Photo day","activities":["Chế Cu Nha","Lao Chải","Dế Su Phình"]},{"day":3,"title":"Return","activities":["Khau Phạ pass","Hà Nội"]}]',
    15,
    NOW(),
    NOW()
  ),
  -- Bangkok
  (
    21,
    'Bangkok City 3N2Đ',
    'bangkok-city-3n2d',
    'Thăm chùa Vàng, chợ nổi và thưởng thức ẩm thực Thái.',
    'Thành phố sôi động Bangkok.',
    '/uploads/avatars/bankok.jpg',
    3,
    8500000,
    9500000,
    4.6,
    187,
    '["City", "Shopping"]',
    1,
    '[{"icon":"temple","text":"Chùa Vàng"},{"icon":"market","text":"Chợ nổi Damnoen"}]',
    '[{"day":1,"title":"Temples","activities":["Chùa Vàng","Wat Pho","Wat Arun"]},{"day":2,"title":"Floating market","activities":["Chợ nổi","Train market","Asiatique"]},{"day":3,"title":"Shopping","activities":["Platinum","MBK","Siam Paragon"]}]',
    17,
    NOW(),
    NOW()
  ),
  -- Phuket
  (
    22,
    'Phuket Beach 4N3Đ',
    'phuket-beach-4n3d',
    'Tắm biển Patong, Phi Phi Island và tham quan đảo.',
    'Thiên đường biển Thái Lan.',
    '/uploads/avatars/phuket.jpg',
    4,
    10500000,
    12000000,
    4.8,
    298,
    '["Beach", "Island"]',
    1,
    '[{"icon":"island","text":"Phi Phi Island"},{"icon":"beach","text":"Patong Beach"}]',
    '[{"day":1,"title":"Arrival","activities":["Patong Beach","Bangla Road"]},{"day":2,"title":"Phi Phi","activities":["Phi Phi Island","Maya Bay","Snorkeling"]},{"day":3,"title":"Phuket tour","activities":["Big Buddha","Wat Chalong","Kata Beach"]},{"day":4,"title":"Shopping","activities":["Jungceylon","Check-out"]}]',
    16,
    NOW(),
    NOW()
  ),
  -- Bali
  (
    23,
    'Bali Cultural 5N4Đ',
    'bali-cultural-5n4d',
    'Khám phá đền Tanah Lot, Ubud và bãi biển Seminyak.',
    'Đảo của các vị thần.',
    '/uploads/avatars/bali.jpg',
    5,
    13800000,
    15500000,
    4.9,
    412,
    '["Beach", "Culture"]',
    1,
    '[{"icon":"temple","text":"Đền Tanah Lot"},{"icon":"monkey","text":"Ubud Monkey Forest"}]',
    '[{"day":1,"title":"Arrival Ubud","activities":["Tegalalang rice terrace","Ubud Palace"]},{"day":2,"title":"Water temples","activities":["Tirta Empul","Tegenungan waterfall"]},{"day":3,"title":"Tanah Lot","activities":["Tanah Lot sunset","Seminyak"]},{"day":4,"title":"Beach day","activities":["Seminyak Beach","Spa"]},{"day":5,"title":"Uluwatu","activities":["Uluwatu Temple","Kecak dance","Check-out"]}]',
    18,
    NOW(),
    NOW()
  ),
  -- Singapore
  (
    24,
    'Singapore Highlights 3N2Đ',
    'singapore-highlights-3n2d',
    'Gardens by the Bay, Marina Bay Sands và Universal Studios.',
    'Quốc đảo sư tử.',
    '/uploads/avatars/singapore.jpg',
    3,
    15200000,
    17000000,
    4.7,
    234,
    '["City", "Theme Park"]',
    1,
    '[{"icon":"garden","text":"Gardens by the Bay"},{"icon":"ferris-wheel","text":"Singapore Flyer"}]',
    '[{"day":1,"title":"City tour","activities":["Marina Bay Sands","Gardens by the Bay","Merlion"]},{"day":2,"title":"Universal Studios","activities":["Sentosa","Universal Studios","S.E.A. Aquarium"]},{"day":3,"title":"Shopping","activities":["Orchard Road","Chinatown","Check-out"]}]',
    19,
    NOW(),
    NOW()
  ),
  -- Tokyo
  (
    25,
    'Tokyo Discovery 5N4Đ',
    'tokyo-discovery-5n4d',
    'Shibuya, Akihabara, Asakusa và núi Phú Sĩ.',
    'Thành phố hiện đại nhất thế giới.',
    '/uploads/avatars/Tokyo.jpg',
    5,
    23800000,
    27000000,
    4.9,
    567,
    '["City", "Culture"]',
    1,
    '[{"icon":"tower","text":"Tokyo Tower & Sky Tree"},{"icon":"mountain","text":"Mount Fuji"}]',
    '[{"day":1,"title":"Modern Tokyo","activities":["Shibuya Crossing","Harajuku","Shinjuku"]},{"day":2,"title":"Traditional","activities":["Asakusa","Senso-ji","Imperial Palace"]},{"day":3,"title":"Mount Fuji","activities":["Fuji 5th station","Lake Kawaguchi"]},{"day":4,"title":"Akihabara & Ginza","activities":["Electronics","Shopping","Dining"]},{"day":5,"title":"Odaiba","activities":["TeamLab","Gundam","Check-out"]}]',
    21,
    NOW(),
    NOW()
  ),
  -- Seoul
  (
    26,
    'Seoul K-Culture 4N3Đ',
    'seoul-k-culture-4n3d',
    'Cung điện Gyeongbokgung, Myeongdong và làn sóng Hallyu.',
    'Trung tâm K-pop.',
    '/uploads/avatars/Seoul.jpg',
    4,
    14200000,
    16000000,
    4.8,
    389,
    '["City", "Culture"]',
    1,
    '[{"icon":"palace","text":"Gyeongbokgung"},{"icon":"music","text":"K-pop culture"}]',
    '[{"day":1,"title":"Palace day","activities":["Gyeongbokgung","Bukchon Hanok","Insadong"]},{"day":2,"title":"Modern Seoul","activities":["Gangnam","COEX","Han River"]},{"day":3,"title":"Shopping","activities":["Myeongdong","Hongdae","Night market"]},{"day":4,"title":"DMZ tour","activities":["DMZ","Imjingak","Check-out"]}]',
    23,
    NOW(),
    NOW()
  ),
  -- Paris
  (
    27,
    'Paris Romance 5N4Đ',
    'paris-romance-5n4d',
    'Eiffel, Louvre, Versailles và круиз Seine.',
    'Kinh đô ánh sáng.',
    '/uploads/avatars/paris.jpg',
    5,
    28500000,
    32000000,
    4.9,
    678,
    '["City", "Romantic"]',
    1,
    '[{"icon":"tower","text":"Eiffel Tower"},{"icon":"museum","text":"Louvre Museum"}]',
    '[{"day":1,"title":"Arrival","activities":["Eiffel Tower","Champ de Mars","Seine cruise"]},{"day":2,"title":"Museums","activities":["Louvre","Notre Dame","Latin Quarter"]},{"day":3,"title":"Versailles","activities":["Palace of Versailles","Gardens"]},{"day":4,"title":"Montmartre","activities":["Sacré-Cœur","Moulin Rouge","Pigalle"]},{"day":5,"title":"Shopping","activities":["Champs-Élysées","Galeries Lafayette","Check-out"]}]',
    29,
    NOW(),
    NOW()
  ),
  -- London
  (
    28,
    'London Royal 5N4Đ',
    'london-royal-5n4d',
    'Buckingham Palace, British Museum và Harry Potter tour.',
    'Thành phố hoàng gia.',
    '/uploads/avatars/London.jpg',
    5,
    27800000,
    31000000,
    4.8,
    512,
    '["City", "Heritage"]',
    1,
    '[{"icon":"crown","text":"Buckingham Palace"},{"icon":"bridge","text":"Tower Bridge"}]',
    '[{"day":1,"title":"Royal London","activities":["Buckingham Palace","Westminster Abbey","Big Ben"]},{"day":2,"title":"Museums","activities":["British Museum","National Gallery","Covent Garden"]},{"day":3,"title":"Harry Potter","activities":["Platform 9¾","Studio Tour","Oxford Street"]},{"day":4,"title":"Tower & Thames","activities":["Tower of London","Tower Bridge","Thames cruise"]},{"day":5,"title":"Shopping","activities":["Harrods","Camden Market","Check-out"]}]',
    30,
    NOW(),
    NOW()
  ),
  -- Rome
  (
    29,
    'Rome Ancient 4N3Đ',
    'rome-ancient-4n3d',
    'Colosseum, Vatican và Trevi Fountain.',
    'Thành phố vĩnh cửu.',
    '/uploads/avatars/Rome.jpg',
    4,
    24500000,
    28000000,
    4.9,
    589,
    '["City", "Heritage"]',
    1,
    '[{"icon":"colosseum","text":"Colosseum"},{"icon":"church","text":"Vatican City"}]',
    '[{"day":1,"title":"Ancient Rome","activities":["Colosseum","Roman Forum","Palatine Hill"]},{"day":2,"title":"Vatican","activities":["St. Peter''s Basilica","Sistine Chapel","Vatican Museums"]},{"day":3,"title":"Centro Storico","activities":["Trevi Fountain","Pantheon","Spanish Steps"]},{"day":4,"title":"Trastevere","activities":["Trastevere district","Villa Borghese","Check-out"]}]',
    31,
    NOW(),
    NOW()
  ),
  -- Dubai
  (
    30,
    'Dubai Luxury 4N3Đ',
    'dubai-luxury-4n3d',
    'Burj Khalifa, Dubai Mall, sa mạc Safari.',
    'Thành phố xa hoa.',
    '/uploads/avatars/Dubai.jpg',
    4,
    32800000,
    36000000,
    4.8,
    445,
    '["City", "Luxury"]',
    1,
    '[{"icon":"tower","text":"Burj Khalifa"},{"icon":"desert","text":"Desert Safari"}]',
    '[{"day":1,"title":"Modern Dubai","activities":["Burj Khalifa","Dubai Mall","Fountain show"]},{"day":2,"title":"Desert Safari","activities":["Dune bashing","BBQ dinner","Belly dance"]},{"day":3,"title":"Beach & Old Dubai","activities":["Jumeirah Beach","Gold Souk","Spice Souk"]},{"day":4,"title":"Palm Jumeirah","activities":["Atlantis","The View","Check-out"]}]',
    43,
    NOW(),
    NOW()
  ),
  -- Sydney
  (
    31,
    'Sydney Highlights 4N3Đ',
    'sydney-highlights-4n3d',
    'Opera House, Harbour Bridge, Bondi Beach.',
    'Thành phố cảng xinh đẹp.',
    '/uploads/avatars/Sydney.jpg',
    4,
    19800000,
    22000000,
    4.7,
    334,
    '["City", "Beach"]',
    1,
    '[{"icon":"opera","text":"Opera House"},{"icon":"beach","text":"Bondi Beach"}]',
    '[{"day":1,"title":"Harbour","activities":["Opera House","Harbour Bridge","Circular Quay"]},{"day":2,"title":"Beaches","activities":["Bondi Beach","Coogee","Coastal walk"]},{"day":3,"title":"Wildlife","activities":["Taronga Zoo","Darling Harbour"]},{"day":4,"title":"Blue Mountains","activities":["Three Sisters","Scenic World","Check-out"]}]',
    41,
    NOW(),
    NOW()
  ),
  -- New York
  (
    32,
    'New York Manhattan 5N4Đ',
    'new-york-manhattan-5n4d',
    'Times Square, Central Park, Statue of Liberty.',
    'Thành phố không bao giờ ngủ.',
    '/uploads/avatars/New York.png',
    5,
    29800000,
    33000000,
    4.9,
    712,
    '["City", "Urban"]',
    1,
    '[{"icon":"statue","text":"Statue of Liberty"},{"icon":"park","text":"Central Park"}]',
    '[{"day":1,"title":"Downtown","activities":["Times Square","Broadway","Rockefeller"]},{"day":2,"title":"Liberty","activities":["Statue of Liberty","Ellis Island","Wall Street"]},{"day":3,"title":"Museums","activities":["MoMA","Natural History","Central Park"]},{"day":4,"title":"Brooklyn","activities":["Brooklyn Bridge","DUMBO","Williamsburg"]},{"day":5,"title":"Shopping","activities":["5th Avenue","SoHo","Check-out"]}]',
    38,
    NOW(),
    NOW()
  ),
  -- Grand Canyon
  (
    33,
    'Grand Canyon Adventure 3N2Đ',
    'grand-canyon-adventure-3n2d',
    'Trekking, helicopter tour và ngắm bình minh tại hẻm núi.',
    'Hẻm núi kỳ vĩ.',
    '/uploads/avatars/Grand Canyon.jpg',
    3,
    25800000,
    29000000,
    4.9,
    234,
    '["Nature", "Adventure"]',
    1,
    '[{"icon":"helicopter","text":"Helicopter tour"},{"icon":"hiking","text":"Rim trail"}]',
    '[{"day":1,"title":"South Rim","activities":["Arrival","Mather Point","Sunset"]},{"day":2,"title":"Helicopter & Hiking","activities":["Helicopter tour","Bright Angel Trail","Visitor Center"]},{"day":3,"title":"Sunrise & Desert View","activities":["Sunrise","Desert View","Check-out"]}]',
    40,
    NOW(),
    NOW()
  ),
  -- Kyoto
  (
    34,
    'Kyoto Temples 4N3Đ',
    'kyoto-temples-4n3d',
    'Fushimi Inari, Kinkaku-ji, Arashiyama bamboo forest.',
    'Cố đô Nhật Bản.',
    '/uploads/avatars/Kyoto.jpg',
    4,
    22800000,
    25000000,
    4.9,
    456,
    '["Culture", "Heritage"]',
    1,
    '[{"icon":"temple","text":"Golden Pavilion"},{"icon":"bamboo","text":"Bamboo Grove"}]',
    '[{"day":1,"title":"Eastern Kyoto","activities":["Fushimi Inari","Kiyomizu-dera","Gion"]},{"day":2,"title":"Golden Pavilion","activities":["Kinkaku-ji","Ryoan-ji","Nijo Castle"]},{"day":3,"title":"Arashiyama","activities":["Bamboo Grove","Monkey Park","Togetsukyo Bridge"]},{"day":4,"title":"Nara day trip","activities":["Todai-ji","Deer park","Check-out"]}]',
    22,
    NOW(),
    NOW()
  ),
  -- Barcelona
  (
    35,
    'Barcelona Gaudi 4N3Đ',
    'barcelona-gaudi-4n3d',
    'Sagrada Familia, Park Güell, Gothic Quarter.',
    'Thành phố nghệ thuật.',
    '/uploads/avatars/Barcelona.jpg',
    4,
    21800000,
    24000000,
    4.8,
    389,
    '["City", "Architecture"]',
    1,
    '[{"icon":"church","text":"Sagrada Familia"},{"icon":"park","text":"Park Güell"}]',
    '[{"day":1,"title":"Gaudí day","activities":["Sagrada Familia","Park Güell","Casa Batlló"]},{"day":2,"title":"Gothic Quarter","activities":["Gothic Quarter","La Rambla","Barcelona Cathedral"]},{"day":3,"title":"Beach & Montjuïc","activities":["Barceloneta Beach","Montjuïc","Magic Fountain"]},{"day":4,"title":"Shopping","activities":["Passeig de Gràcia","Boqueria Market","Check-out"]}]',
    32,
    NOW(),
    NOW()
  ),
  -- Istanbul
  (
    36,
    'Istanbul East-West 4N3Đ',
    'istanbul-east-west-4n3d',
    'Hagia Sophia, Blue Mosque, Grand Bazaar, Bosphorus cruise.',
    'Cầu nối Á-Âu.',
    '/uploads/avatars/Istanbul.jpg',
    4,
    16800000,
    19000000,
    4.7,
    312,
    '["City", "Culture"]',
    1,
    '[{"icon":"mosque","text":"Blue Mosque"},{"icon":"bazaar","text":"Grand Bazaar"}]',
    '[{"day":1,"title":"Sultanahmet","activities":["Hagia Sophia","Blue Mosque","Hippodrome"]},{"day":2,"title":"Palaces","activities":["Topkapi Palace","Basilica Cistern","Grand Bazaar"]},{"day":3,"title":"Bosphorus","activities":["Bosphorus cruise","Dolmabahçe Palace","Taksim"]},{"day":4,"title":"Asian side","activities":["Üsküdar","Maiden''s Tower","Check-out"]}]',
    37,
    NOW(),
    NOW()
  ),
  -- Santorini
  (
    37,
    'Santorini Romance 3N2Đ',
    'santorini-romance-3n2d',
    'Oia sunset, Red Beach, wine tasting.',
    'Hòn đảo hoàng hôn.',
    '/uploads/avatars/Santorini.jpg',
    3,
    24800000,
    28000000,
    4.9,
    445,
    '["Island", "Romantic"]',
    1,
    '[{"icon":"sunset","text":"Oia sunset"},{"icon":"wine","text":"Wine tasting"}]',
    '[{"day":1,"title":"Arrival Fira","activities":["Fira town","Caldera walk","Sunset"]},{"day":2,"title":"Oia & Beaches","activities":["Oia village","Red Beach","Black Beach"]},{"day":3,"title":"Wine & Akrotiri","activities":["Wine tasting","Akrotiri ruins","Check-out"]}]',
    36,
    NOW(),
    NOW()
  ),
  -- Kuala Lumpur
  (
    38,
    'KL City 3N2Đ',
    'kl-city-3n2d',
    'Petronas Towers, Batu Caves, Chinatown.',
    'Thành phố đa văn hóa.',
    '/uploads/avatars/kuala-lumpur.jpg',
    3,
    11800000,
    13500000,
    4.6,
    267,
    '["City", "Shopping"]',
    0,
    '[{"icon":"towers","text":"Petronas Towers"},{"icon":"temple","text":"Batu Caves"}]',
    '[{"day":1,"title":"City center","activities":["Petronas Towers","KLCC Park","Bukit Bintang"]},{"day":2,"title":"Culture","activities":["Batu Caves","Chinatown","Central Market"]},{"day":3,"title":"Shopping","activities":["Pavilion KL","Suria KLCC","Check-out"]}]',
    20,
    NOW(),
    NOW()
  ),
  -- Busan
  (
    39,
    'Busan Coastal 3N2Đ',
    'busan-coastal-3n2d',
    'Haeundae Beach, Gamcheon village, Jagalchi fish market.',
    'Thành phố cảng Hàn Quốc.',
    '/uploads/avatars/Busan.jpg',
    3,
    12800000,
    14500000,
    4.7,
    198,
    '["City", "Beach"]',
    0,
    '[{"icon":"beach","text":"Haeundae Beach"},{"icon":"village","text":"Gamcheon Culture Village"}]',
    '[{"day":1,"title":"Beach day","activities":["Haeundae Beach","Dongbaek Island","BIFF Square"]},{"day":2,"title":"Culture","activities":["Gamcheon Village","Beomeosa Temple","Seomyeon"]},{"day":3,"title":"Market","activities":["Jagalchi Market","Taejongdae","Check-out"]}]',
    24,
    NOW(),
    NOW()
  ),
  -- Amsterdam
  (
    40,
    'Amsterdam Canals 3N2Đ',
    'amsterdam-canals-3n2d',
    'Van Gogh Museum, Anne Frank House, canal cruise.',
    'Thành phố kênh đào.',
    '/uploads/avatars/Amsterdam.jpg',
    3,
    18800000,
    21000000,
    4.8,
    389,
    '["City", "Culture"]',
    0,
    '[{"icon":"canal","text":"Canal cruise"},{"icon":"museum","text":"Van Gogh Museum"}]',
    '[{"day":1,"title":"Museums","activities":["Van Gogh Museum","Rijksmuseum","I amsterdam"]},{"day":2,"title":"Anne Frank","activities":["Anne Frank House","Jordan district","Canal cruise"]},{"day":3,"title":"Windmills","activities":["Zaanse Schans","Volendam","Check-out"]}]',
    33,
    NOW(),
    NOW()
  ),
  -- Prague
  (
    41,
    'Prague Fairytale 3N2Đ',
    'prague-fairytale-3n2d',
    'Prague Castle, Charles Bridge, Old Town Square.',
    'Thành phố cổ tích.',
    '/uploads/avatars/Prague.jpg',
    3,
    14800000,
    16500000,
    4.8,
    312,
    '["City", "Heritage"]',
    0,
    '[{"icon":"castle","text":"Prague Castle"},{"icon":"bridge","text":"Charles Bridge"}]',
    '[{"day":1,"title":"Castle & Bridge","activities":["Prague Castle","St. Vitus Cathedral","Charles Bridge"]},{"day":2,"title":"Old Town","activities":["Old Town Square","Astronomical Clock","Jewish Quarter"]},{"day":3,"title":"Modern Prague","activities":["Wenceslas Square","Dancing House","Check-out"]}]',
    34,
    NOW(),
    NOW()
  ),
  -- Vienna
  (
    42,
    'Vienna Music 3N2Đ',
    'vienna-music-3n2d',
    'Schönbrunn Palace, Vienna Opera, Hofburg Palace.',
    'Thủ đô âm nhạc.',
    '/uploads/avatars/vienna.jpg',
    3,
    16800000,
    18500000,
    4.7,
    256,
    '["City", "Culture"]',
    0,
    '[{"icon":"palace","text":"Schönbrunn Palace"},{"icon":"music","text":"Vienna Opera"}]',
    '[{"day":1,"title":"Palaces","activities":["Schönbrunn Palace","Hofburg Palace","Stephansdom"]},{"day":2,"title":"Music & Art","activities":["Vienna Opera","Kunsthistorisches Museum","Naschmarkt"]},{"day":3,"title":"Coffee culture","activities":["Café culture","Belvedere Palace","Check-out"]}]',
    35,
    NOW(),
    NOW()
  ),
  -- Los Angeles
  (
    43,
    'LA Hollywood 4N3Đ',
    'la-hollywood-4n3d',
    'Hollywood, Universal Studios, Santa Monica.',
    'Thành phố thiên thần.',
    '/uploads/avatars/Los Angeles.jpg',
    4,
    26800000,
    29000000,
    4.6,
    423,
    '["City", "Entertainment"]',
    0,
    '[{"icon":"star","text":"Hollywood Walk of Fame"},{"icon":"theme-park","text":"Universal Studios"}]',
    '[{"day":1,"title":"Hollywood","activities":["Walk of Fame","TCL Chinese Theatre","Griffith Observatory"]},{"day":2,"title":"Universal","activities":["Universal Studios","CityWalk"]},{"day":3,"title":"Beach","activities":["Santa Monica Pier","Venice Beach","Beverly Hills"]},{"day":4,"title":"Downtown","activities":["Getty Center","LACMA","Check-out"]}]',
    39,
    NOW(),
    NOW()
  ) ON DUPLICATE KEY
UPDATE `name` =
VALUES
  (`name`),
  `description` =
VALUES
  (`description`),
  `image` =
VALUES
  (`image`),
  `price` =
VALUES
  (`price`),
  `rating` =
VALUES
  (`rating`),
  `featured` =
VALUES
  (`featured`);

-- ============================================
-- HOTELS (30+ hotels với ảnh và giá chi tiết)
-- ============================================
INSERT INTO
  `Hotel` (
    `id`,
    `name`,
    `slug`,
    `description`,
    `image`,
    `address`,
    `city`,
    `country`,
    `pricePerNight`,
    `rating`,
    `featured`,
    `amenities`,
    `destinationId`,
    `createdAt`,
    `updatedAt`
  )
VALUES
  -- Việt Nam Hotels (20 hotels)
  (
    1,
    'Halong Bay Luxury Resort',
    'halong-bay-luxury-resort',
    'Resort sang trọng với view vịnh Hạ Long tuyệt đẹp và spa đẳng cấp quốc tế.',
    '/uploads/hotels/halong-luxury.jpg',
    'Bãi Cháy, Hạ Long',
    'Hạ Long',
    'Việt Nam',
    2500000,
    4.8,
    1,
    '["wifi", "pool", "spa", "gym", "beach-access", "restaurant"]',
    2,
    NOW(),
    NOW()
  ),
  (
    2,
    'Halong Bay View Hotel',
    'halong-bay-view-hotel',
    'Khách sạn 4 sao view vịnh, gần bến tàu du lịch.',
    '/uploads/hotels/halong-view.jpg',
    'Trung tâm Hạ Long',
    'Hạ Long',
    'Việt Nam',
    1800000,
    4.5,
    0,
    '["wifi", "pool", "restaurant", "parking"]',
    2,
    NOW(),
    NOW()
  ),
  (
    3,
    'Emerald Waters Hotel & Spa Halong',
    'emerald-waters-halong',
    'Khách sạn boutique với dịch vụ chu đáo và ẩm thực cao cấp.',
    '/uploads/hotels/emerald-halong.jpg',
    'Bãi Cháy, Hạ Long',
    'Hạ Long',
    'Việt Nam',
    2200000,
    4.7,
    0,
    '["wifi", "spa", "restaurant", "bar"]',
    2,
    NOW(),
    NOW()
  ),
  (
    4,
    'Phu Quoc Beach Resort',
    'phu-quoc-beach-resort',
    'Resort biển 5 sao với bãi tắm riêng và villas sang trọng.',
    '/uploads/hotels/phuquoc-beach.jpg',
    'Bãi Trường, Phú Quốc',
    'Phú Quốc',
    'Việt Nam',
    3200000,
    4.7,
    1,
    '["wifi", "pool", "beach", "restaurant", "spa", "gym"]',
    4,
    NOW(),
    NOW()
  ),
  (
    5,
    'Phu Quoc Sunset Resort & Spa',
    'phu-quoc-sunset-resort',
    'Resort 5 sao view hoàng hôn, phòng hướng biển.',
    '/uploads/hotels/phuquoc-sunset.jpg',
    'Bãi Khem, Phú Quốc',
    'Phú Quốc',
    'Việt Nam',
    3800000,
    4.9,
    1,
    '["wifi", "pool", "spa", "gym", "beach", "kids-club"]',
    4,
    NOW(),
    NOW()
  ),
  (
    6,
    'Pearl Island Resort Phu Quoc',
    'pearl-island-phu-quoc',
    'Resort sang trọng với thiết kế hiện đại, gần VinWonders.',
    '/uploads/hotels/pearl-phuquoc.jpg',
    'Bãi Dài, Phú Quốc',
    'Phú Quốc',
    'Việt Nam',
    4200000,
    4.8,
    1,
    '["wifi", "pool", "beach", "restaurant", "spa", "water-sports"]',
    4,
    NOW(),
    NOW()
  ),
  (
    7,
    'Hanoi Old Quarter Boutique Hotel',
    'hanoi-old-quarter-hotel',
    'Khách sạn giữa lòng phố cổ, kiến trúc Pháp cổ điển.',
    '/uploads/hotels/hanoi-oldquarter.jpg',
    'Phố cổ Hà Nội',
    'Hà Nội',
    'Việt Nam',
    1500000,
    4.5,
    0,
    '["wifi", "parking", "restaurant", "tour-desk"]',
    5,
    NOW(),
    NOW()
  ),
  (
    8,
    'Hanoi Skyline Luxury Hotel',
    'hanoi-skyline-hotel',
    'Khách sạn 5 sao, rooftop pool, view toàn cảnh thành phố.',
    '/uploads/hotels/hanoi-skyline.jpg',
    'Hoàn Kiếm, Hà Nội',
    'Hà Nội',
    'Việt Nam',
    2000000,
    4.7,
    1,
    '["wifi", "pool", "gym", "spa", "rooftop-bar"]',
    5,
    NOW(),
    NOW()
  ),
  (
    9,
    'Sofitel Legend Metropole Hanoi',
    'sofitel-metropole-hanoi',
    'Khách sạn lịch sử 5 sao, từng đón tiếp nhiều nguyên thủ quốc gia.',
    '/uploads/hotels/sofitel-hanoi.jpg',
    'Hoàn Kiếm, Hà Nội',
    'Hà Nội',
    'Việt Nam',
    4500000,
    4.9,
    1,
    '["wifi", "pool", "spa", "restaurant", "bar", "heritage"]',
    5,
    NOW(),
    NOW()
  ),
  (
    10,
    'Da Nang Beach Resort & Spa',
    'da-nang-beach-resort',
    'Resort biển với bãi tắm Mỹ Khê, spa và nhà hàng quốc tế.',
    '/uploads/hotels/danang-beach.jpg',
    'Mỹ Khê, Đà Nẵng',
    'Đà Nẵng',
    'Việt Nam',
    2800000,
    4.6,
    1,
    '["wifi", "pool", "beach", "spa", "restaurant"]',
    6,
    NOW(),
    NOW()
  ),
  (
    11,
    'Hyatt Regency Danang',
    'hyatt-danang',
    'Resort 5 sao với kiến trúc độc đáo, view biển và núi.',
    '/uploads/hotels/hyatt-danang.jpg',
    'Sơn Trà, Đà Nẵng',
    'Đà Nẵng',
    'Việt Nam',
    4000000,
    4.9,
    1,
    '["wifi", "pool", "spa", "gym", "beach", "kids-club"]',
    6,
    NOW(),
    NOW()
  ),
  (
    12,
    'Da Lat Mountain View Resort',
    'da-lat-mountain-resort',
    'Resort view núi, sương mù và vườn hoa.',
    '/uploads/hotels/dalat-mountain.jpg',
    'Trung tâm Đà Lạt',
    'Đà Lạt',
    'Việt Nam',
    1800000,
    4.4,
    0,
    '["wifi", "parking", "garden", "restaurant"]',
    3,
    NOW(),
    NOW()
  ),
  (
    13,
    'Dalat Terrasse des Roses Villa',
    'dalat-terrasse-villa',
    'Villa phong cách Pháp với vườn hồng và view thung lũng.',
    '/uploads/hotels/dalat-villa.jpg',
    'Phường 3, Đà Lạt',
    'Đà Lạt',
    'Việt Nam',
    2200000,
    4.7,
    1,
    '["wifi", "garden", "fireplace", "restaurant"]',
    3,
    NOW(),
    NOW()
  ),
  (
    14,
    'Hoi An Riverside Resort',
    'hoi-an-riverside-resort',
    'Resort bên sông, shuttle tới phố cổ.',
    '/uploads/hotels/hoian-riverside.jpg',
    'Bờ sông Hoài, Hội An',
    'Hội An',
    'Việt Nam',
    2200000,
    4.7,
    1,
    '["wifi", "pool", "spa", "shuttle", "restaurant"]',
    8,
    NOW(),
    NOW()
  ),
  (
    15,
    'Anantara Hoi An Resort',
    'anantara-hoi-an',
    'Resort 5 sao bên sông Thu Bồn với dịch vụ đẳng cấp.',
    '/uploads/hotels/anantara-hoian.jpg',
    'Cẩm Châu, Hội An',
    'Hội An',
    'Việt Nam',
    3500000,
    4.9,
    1,
    '["wifi", "pool", "spa", "gym", "restaurant", "bar"]',
    8,
    NOW(),
    NOW()
  ),
  (
    16,
    'Nha Trang Oceanic Hotel',
    'nha-trang-oceanic-hotel',
    'Khách sạn view biển, gần Vinpearl.',
    '/uploads/hotels/nhatrang-oceanic.jpg',
    'Trần Phú, Nha Trang',
    'Nha Trang',
    'Việt Nam',
    2000000,
    4.6,
    0,
    '["wifi", "pool", "beach", "restaurant"]',
    12,
    NOW(),
    NOW()
  ),
  (
    17,
    'InterContinental Nha Trang',
    'intercontinental-nha-trang',
    'Resort 5 sao sang trọng với spa và ẩm thực đa dạng.',
    '/uploads/hotels/intercontinental-nhatrang.jpg',
    'Bãi Tắm, Nha Trang',
    'Nha Trang',
    'Việt Nam',
    3800000,
    4.9,
    1,
    '["wifi", "pool", "spa", "gym", "beach", "kids-club"]',
    12,
    NOW(),
    NOW()
  ),
  (
    18,
    'Sapa Charm Hotel',
    'sapa-charm-hotel',
    'Khách sạn boutique view ruộng bậc thang.',
    '/uploads/hotels/sapa-charm.jpg',
    'Trung tâm Sa Pa',
    'Sa Pa',
    'Việt Nam',
    1400000,
    4.5,
    0,
    '["wifi", "parking", "restaurant", "tour-desk"]',
    7,
    NOW(),
    NOW()
  ),
  (
    19,
    'Victoria Sapa Resort',
    'victoria-sapa',
    'Resort phong cách Pháp cổ điển với fireplace và spa.',
    '/uploads/hotels/victoria-sapa.jpg',
    'Xuân Viên, Sa Pa',
    'Sa Pa',
    'Việt Nam',
    2800000,
    4.8,
    1,
    '["wifi", "spa", "restaurant", "fireplace", "gym"]',
    7,
    NOW(),
    NOW()
  ),
  (
    20,
    'Ninh Binh Eco Resort',
    'ninh-binh-eco-resort',
    'Resort sinh thái giữa thiên nhiên núi rừng.',
    '/uploads/hotels/ninhbinh-eco.jpg',
    'Tràng An, Ninh Bình',
    'Ninh Bình',
    'Việt Nam',
    1600000,
    4.6,
    0,
    '["wifi", "pool", "restaurant", "garden", "bike-rental"]',
    1,
    NOW(),
    NOW()
  ),
  -- Quốc tế Hotels (15 hotels)
  (
    21,
    'Patong Beach Resort Phuket',
    'patong-beach-phuket',
    'Resort bãi biển Patong với pool bar và spa.',
    '/uploads/hotels/patong-phuket.jpg',
    'Patong Beach, Phuket',
    'Phuket',
    'Thái Lan',
    3500000,
    4.6,
    1,
    '["wifi", "pool", "beach", "spa", "restaurant"]',
    16,
    NOW(),
    NOW()
  ),
  (
    22,
    'Le Meridien Phuket Beach',
    'lemeridien-phuket',
    'Resort 5 sao trên bãi Karon với thiết kế hiện đại.',
    '/uploads/hotels/lemeridien-phuket.jpg',
    'Karon Beach, Phuket',
    'Phuket',
    'Việt Nam',
    4200000,
    4.8,
    1,
    '["wifi", "pool", "spa", "gym", "beach", "kids-club"]',
    16,
    NOW(),
    NOW()
  ),
  (
    23,
    'Bangkok Riverside Hotel',
    'bangkok-riverside-hotel',
    'Khách sạn bên sông Chao Phraya, shuttle tới BTS.',
    '/uploads/hotels/bangkok-riverside.jpg',
    'Riverside, Bangkok',
    'Bangkok',
    'Thái Lan',
    2800000,
    4.5,
    0,
    '["wifi", "pool", "restaurant", "shuttle", "river-view"]',
    17,
    NOW(),
    NOW()
  ),
  (
    24,
    'Mandarin Oriental Bangkok',
    'mandarin-oriental-bangkok',
    'Khách sạn huyền thoại bên sông với dịch vụ đẳng cấp thế giới.',
    '/uploads/hotels/mandarin-bangkok.jpg',
    'Charoenkrung, Bangkok',
    'Bangkok',
    'Thái Lan',
    8500000,
    4.9,
    1,
    '["wifi", "pool", "spa", "restaurant", "bar", "heritage"]',
    17,
    NOW(),
    NOW()
  ),
  (
    25,
    'Ubud Jungle Resort Bali',
    'ubud-jungle-bali',
    'Resort giữa rừng nhiệt đới với infinity pool.',
    '/uploads/hotels/ubud-jungle.jpg',
    'Ubud, Bali',
    'Bali',
    'Indonesia',
    4500000,
    4.8,
    1,
    '["wifi", "pool", "spa", "restaurant", "yoga", "jungle-view"]',
    18,
    NOW(),
    NOW()
  ),
  (
    26,
    'Seminyak Beach Club Hotel',
    'seminyak-beach-bali',
    'Hotel view biển Seminyak với beach club sôi động.',
    '/uploads/hotels/seminyak-bali.jpg',
    'Seminyak, Bali',
    'Bali',
    'Indonesia',
    3800000,
    4.7,
    1,
    '["wifi", "pool", "beach", "restaurant", "bar", "beach-club"]',
    18,
    NOW(),
    NOW()
  ),
  (
    27,
    'Marina Bay Sands Singapore',
    'marina-bay-sands-singapore',
    'Khách sạn biểu tượng với rooftop pool và casino.',
    '/uploads/hotels/mbs-singapore.jpg',
    'Marina Bay, Singapore',
    'Singapore',
    'Singapore',
    12000000,
    4.9,
    1,
    '["wifi", "rooftop-pool", "spa", "casino", "shopping", "restaurant"]',
    19,
    NOW(),
    NOW()
  ),
  (
    28,
    'Raffles Hotel Singapore',
    'raffles-singapore',
    'Khách sạn lịch sử sang trọng từ năm 1887.',
    '/uploads/hotels/raffles-singapore.jpg',
    'Beach Road, Singapore',
    'Singapore',
    'Singapore',
    15000000,
    4.9,
    1,
    '["wifi", "pool", "spa", "restaurant", "bar", "heritage"]',
    19,
    NOW(),
    NOW()
  ),
  (
    29,
    'Park Hyatt Tokyo',
    'park-hyatt-tokyo',
    'Khách sạn cao cấp tầng 39-52 với view Mount Fuji.',
    '/uploads/hotels/park-hyatt-tokyo.jpg',
    'Shinjuku, Tokyo',
    'Tokyo',
    'Nhật Bản',
    18000000,
    4.9,
    1,
    '["wifi", "pool", "spa", "gym", "restaurant", "bar"]',
    21,
    NOW(),
    NOW()
  ),
  (
    30,
    'Four Seasons Seoul',
    'four-seasons-seoul',
    'Khách sạn 5 sao giữa lòng Gangnam với spa đẳng cấp.',
    '/uploads/hotels/fourseasons-seoul.jpg',
    'Gangnam, Seoul',
    'Seoul',
    'Hàn Quốc',
    12000000,
    4.9,
    1,
    '["wifi", "pool", "spa", "gym", "restaurant", "bar"]',
    23,
    NOW(),
    NOW()
  ),
  (
    31,
    'Hôtel Plaza Athénée Paris',
    'plaza-athenee-paris',
    'Khách sạn huyền thoại trên Avenue Montaigne.',
    '/uploads/hotels/plaza-paris.jpg',
    '8th arr., Paris',
    'Paris',
    'Pháp',
    25000000,
    4.9,
    1,
    '["wifi", "spa", "restaurant", "bar", "luxury", "heritage"]',
    29,
    NOW(),
    NOW()
  ),
  (
    32,
    'The Savoy London',
    'the-savoy-london',
    'Khách sạn lịch sử sang trọng bên Thames.',
    '/uploads/hotels/savoy-london.jpg',
    'Strand, London',
    'London',
    'Anh',
    22000000,
    4.9,
    1,
    '["wifi", "spa", "restaurant", "bar", "heritage", "river-view"]',
    30,
    NOW(),
    NOW()
  ),
  (
    33,
    'Hotel Danieli Venice',
    'danieli-venice',
    'Khách sạn cung điện Gothic hướng lagoon Venice.',
    '/uploads/hotels/danieli-venice.jpg',
    'San Marco, Venice',
    'Venice',
    'Ý',
    20000000,
    4.9,
    1,
    '["wifi", "restaurant", "bar", "heritage", "lagoon-view"]',
    31,
    NOW(),
    NOW()
  ),
  (
    34,
    'Burj Al Arab Dubai',
    'burj-al-arab-dubai',
    'Khách sạn 7 sao biểu tượng Dubai trên đảo nhân tạo.',
    '/uploads/hotels/burj-al-arab.jpg',
    'Jumeirah, Dubai',
    'Dubai',
    'UAE',
    45000000,
    5.0,
    1,
    '["wifi", "pool", "spa", "restaurant", "bar", "private-beach", "luxury"]',
    43,
    NOW(),
    NOW()
  ),
  (
    35,
    'The Langham Sydney',
    'langham-sydney',
    'Khách sạn sang trọng tại The Rocks với view Harbour.',
    '/uploads/hotels/langham-sydney.jpg',
    'The Rocks, Sydney',
    'Sydney',
    'Úc',
    15000000,
    4.8,
    1,
    '["wifi", "pool", "spa", "gym", "restaurant", "harbour-view"]',
    41,
    NOW(),
    NOW()
  ) ON DUPLICATE KEY
UPDATE `name` =
VALUES
  (`name`),
  `description` =
VALUES
  (`description`),
  `image` =
VALUES
  (`image`),
  `pricePerNight` =
VALUES
  (`pricePerNight`),
  `rating` =
VALUES
  (`rating`),
  `featured` =
VALUES
  (`featured`);

-- ============================================
-- RESTAURANTS (30+ restaurants với ảnh và giá)
-- ============================================
INSERT INTO
  `Restaurant` (
    `id`,
    `name`,
    `slug`,
    `description`,
    `image`,
    `address`,
    `city`,
    `country`,
    `cuisine`,
    `priceRange`,
    `rating`,
    `featured`,
    `amenities`,
    `destinationId`,
    `createdAt`,
    `updatedAt`
  )
VALUES
  -- Việt Nam Restaurants (20)
  (
    1,
    'Phở Gia Truyền Bát Đàn',
    'pho-gia-truyen-bat-dan',
    'Phở bò nổi tiếng Hà Nội, nước dùng đậm đà từ xương hầm 12 tiếng.',
    '/uploads/restaurants/pho-batdan.jpg',
    '49 Bát Đàn, Hoàn Kiếm',
    'Hà Nội',
    'Việt Nam',
    'Việt Nam',
    '50.000-80.000đ',
    4.8,
    1,
    '["wifi", "takeaway", "local-favorite"]',
    5,
    NOW(),
    NOW()
  ),
  (
    2,
    'Bún Chả Hương Liên',
    'bun-cha-huong-lien',
    'Bún chả Obama - nơi Tổng thống Obama đã dùng bữa.',
    '/uploads/restaurants/buncha-obama.jpg',
    '24 Lê Văn Hưu, Hai Bà Trưng',
    'Hà Nội',
    'Việt Nam',
    'Việt Nam',
    '40.000-70.000đ',
    4.7,
    1,
    '["wifi", "famous", "local-favorite"]',
    5,
    NOW(),
    NOW()
  ),
  (
    3,
    'Chả Cá Lã Vọng',
    'cha-ca-la-vong',
    'Món chả cá truyền thống Hà Nội từ năm 1871.',
    '/uploads/restaurants/chaca-lavong.jpg',
    '14 Chả Cá, Hoàn Kiếm',
    'Hà Nội',
    'Việt Nam',
    'Việt Nam',
    '150.000-250.000đ',
    4.6,
    1,
    '["wifi", "heritage", "reservation-required"]',
    5,
    NOW(),
    NOW()
  ),
  (
    4,
    'Cà Phê Giảng',
    'ca-phe-giang',
    'Cà phê trứng nguyên bản - đặc sản Hà Nội.',
    '/uploads/restaurants/cafe-giang.jpg',
    '39 Nguyễn Hữu Huân, Hoàn Kiếm',
    'Hà Nội',
    'Việt Nam',
    'Café',
    '30.000-50.000đ',
    4.9,
    1,
    '["wifi", "heritage", "famous"]',
    5,
    NOW(),
    NOW()
  ),
  (
    5,
    'Hải Sản Phú Quốc Xanh',
    'hai-san-phu-quoc-xanh',
    'Hải sản tươi sống view biển, đặc sản ghẹ hấp bia.',
    '/uploads/restaurants/haisan-phuquoc.jpg',
    'Bãi Dài, Phú Quốc',
    'Phú Quốc',
    'Việt Nam',
    'Hải sản',
    '200.000-500.000đ',
    4.7,
    1,
    '["wifi", "outdoor", "sea-view", "parking"]',
    4,
    NOW(),
    NOW()
  ),
  (
    6,
    'Nhà Hàng Hưng Phú Quốc',
    'nha-hang-hung-phu-quoc',
    'Ẩm thực Phú Quốc đặc sản: gỏi cá trích, bún quậy.',
    '/uploads/restaurants/hung-phuquoc.jpg',
    'Dương Đông, Phú Quốc',
    'Phú Quốc',
    'Việt Nam',
    'Việt Nam',
    '100.000-300.000đ',
    4.6,
    0,
    '["wifi", "parking", "local-food"]',
    4,
    NOW(),
    NOW()
  ),
  (
    7,
    'Hải Sản Hạ Long Plaza',
    'hai-san-ha-long-plaza',
    'Nhà hàng hải sản view vịnh Hạ Long, buffet hải sản.',
    '/uploads/restaurants/haisan-halong.jpg',
    'Bãi Cháy, Hạ Long',
    'Hạ Long',
    'Việt Nam',
    'Hải sản',
    '300.000-600.000đ',
    4.7,
    1,
    '["wifi", "bay-view", "buffet", "parking"]',
    2,
    NOW(),
    NOW()
  ),
  (
    8,
    'Cơm Gà Bà Buội Hội An',
    'com-ga-ba-buoi-hoi-an',
    'Cơm gà đặc sản Hội An nổi tiếng từ năm 1950.',
    '/uploads/restaurants/comga-hoian.jpg',
    '22 Phan Chu Trinh, Hội An',
    'Hội An',
    'Việt Nam',
    'Việt Nam',
    '40.000-80.000đ',
    4.6,
    1,
    '["wifi", "heritage", "local-favorite"]',
    8,
    NOW(),
    NOW()
  ),
  (
    9,
    'Cao Lầu Bà Bé',
    'cao-lau-ba-be',
    'Cao lầu nguyên bản với nước giếng Bá Lễ.',
    '/uploads/restaurants/caolau-babe.jpg',
    '45 Trần Phú, Hội An',
    'Hội An',
    'Việt Nam',
    'Việt Nam',
    '30.000-60.000đ',
    4.8,
    1,
    '["wifi", "heritage"]',
    8,
    NOW(),
    NOW()
  ),
  (
    10,
    'Morning Glory Restaurant Hội An',
    'morning-glory-hoi-an',
    'Nhà hàng ẩm thực Hội An cao cấp, cooking class.',
    '/uploads/restaurants/morningglory-hoian.jpg',
    '106 Nguyễn Thái Học, Hội An',
    'Hội An',
    'Việt Nam',
    'Việt Nam',
    '150.000-300.000đ',
    4.9,
    1,
    '["wifi", "cooking-class", "reservation"]',
    8,
    NOW(),
    NOW()
  ),
  (
    11,
    'Hải Sản Mỹ Khê Đà Nẵng',
    'hai-san-my-khe-da-nang',
    'Hải sản tươi sống view biển Mỹ Khê.',
    '/uploads/restaurants/haisan-danang.jpg',
    'Bãi biển Mỹ Khê, Đà Nẵng',
    'Đà Nẵng',
    'Việt Nam',
    'Hải sản',
    '200.000-500.000đ',
    4.8,
    1,
    '["wifi", "outdoor", "beach-view"]',
    6,
    NOW(),
    NOW()
  ),
  (
    12,
    'Bà Thịt Restaurant Đà Nẵng',
    'ba-thit-restaurant-danang',
    'Ẩm thực miền Trung đặc sản: mì Quảng, bún mắm.',
    '/uploads/restaurants/bathit-danang.jpg',
    'Hải Châu, Đà Nẵng',
    'Đà Nẵng',
    'Việt Nam',
    'Việt Nam',
    '50.000-150.000đ',
    4.6,
    0,
    '["wifi", "parking", "local-food"]',
    6,
    NOW(),
    NOW()
  ),
  (
    13,
    'Lẩu Gà Đen Đà Lạt',
    'lau-ga-den-da-lat',
    'Đặc sản lẩu gà đen Đà Lạt, rau củ tươi từ nông trại.',
    '/uploads/restaurants/lauga-dalat.jpg',
    'Khu Hòa Bình, Đà Lạt',
    'Đà Lạt',
    'Việt Nam',
    'Việt Nam',
    '150.000-300.000đ',
    4.7,
    1,
    '["wifi", "parking", "local-specialty"]',
    3,
    NOW(),
    NOW()
  ),
  (
    14,
    'Trâm Restaurant Đà Lạt',
    'tram-restaurant-da-lat',
    'Ẩm thực Đà Lạt sang trọng với view thành phố.',
    '/uploads/restaurants/tram-dalat.jpg',
    'Trần Hưng Đạo, Đà Lạt',
    'Đà Lạt',
    'Việt Nam',
    'Việt Nam',
    '200.000-400.000đ',
    4.8,
    1,
    '["wifi", "city-view", "romantic"]',
    3,
    NOW(),
    NOW()
  ),
  (
    15,
    'Hải Sản Lanterns Nha Trang',
    'hai-san-lanterns-nha-trang',
    'Nhà hàng hải sản view biển với BBQ seafood.',
    '/uploads/restaurants/lanterns-nhatrang.jpg',
    'Trần Phú, Nha Trang',
    'Nha Trang',
    'Việt Nam',
    'Hải sản',
    '250.000-600.000đ',
    4.7,
    1,
    '["wifi", "sea-view", "bbq"]',
    12,
    NOW(),
    NOW()
  ),
  (
    16,
    'Bún Bò Huế Đông Ba',
    'bun-bo-hue-dong-ba',
    'Bún bò Huế đậm đà, chuẩn vị cố đô.',
    '/uploads/restaurants/bunbo-hue.jpg',
    'Đông Ba, Huế',
    'Huế',
    'Việt Nam',
    'Việt Nam',
    '40.000-70.000đ',
    4.8,
    1,
    '["wifi", "local-favorite"]',
    9,
    NOW(),
    NOW()
  ),
  (
    17,
    'Cơm Hến Huế',
    'com-hen-hue',
    'Món ăn bình dân đặc sắc của Huế.',
    '/uploads/restaurants/comhen-hue.jpg',
    'Phạm Hồng Thái, Huế',
    'Huế',
    'Việt Nam',
    'Việt Nam',
    '20.000-40.000đ',
    4.6,
    0,
    '["takeaway", "street-food"]',
    9,
    NOW(),
    NOW()
  ),
  (
    18,
    'Lẩu Mắm U Tròn Cần Thơ',
    'lau-mam-u-tron-can-tho',
    'Lẩu mắm đặc sản miền Tây với hải sản và rau rừng.',
    '/uploads/restaurants/laumam-cantho.jpg',
    'Ninh Kiều, Cần Thơ',
    'Cần Thơ',
    'Việt Nam',
    'Việt Nam',
    '150.000-300.000đ',
    4.7,
    1,
    '["wifi", "parking", "local-specialty"]',
    10,
    NOW(),
    NOW()
  ),
  (
    19,
    'Bánh Căn Vũng Tàu',
    'banh-can-vung-tau',
    'Bánh căn nổi tiếng Vũng Tàu với tôm tươi.',
    '/uploads/restaurants/banhcan-vungtau.jpg',
    'Thùy Vân, Vũng Tàu',
    'Vũng Tàu',
    'Việt Nam',
    'Việt Nam',
    '30.000-50.000đ',
    4.5,
    0,
    '["street-food", "local-favorite"]',
    11,
    NOW(),
    NOW()
  ),
  (
    20,
    'Bánh Xèo Tạ Quy Nhơn',
    'banh-xeo-ta-quy-nhon',
    'Bánh xèo đặc sản Quy Nhơn với tôm tươi và giá đỗ.',
    '/uploads/restaurants/banhxeo-quynhon.jpg',
    'Lê Hồng Phong, Quy Nhơn',
    'Quy Nhơn',
    'Việt Nam',
    'Việt Nam',
    '40.000-80.000đ',
    4.6,
    0,
    '["local-specialty", "outdoor"]',
    13,
    NOW(),
    NOW()
  ),
  -- Quốc tế Restaurants (15)
  (
    21,
    'Laem Hin Seafood Phuket',
    'laem-hin-phuket',
    'Nhà hàng hải sản view biển nổi tiếng Phuket.',
    '/uploads/restaurants/laemhin-phuket.jpg',
    'Rawai, Phuket',
    'Phuket',
    'Thái Lan',
    'Hải sản',
    '200-500 THB',
    4.7,
    1,
    '["wifi", "sea-view", "parking"]',
    16,
    NOW(),
    NOW()
  ),
  (
    22,
    'Baan Rim Pa Phuket',
    'baan-rim-pa-phuket',
    'Nhà hàng Thái cao cấp trên vách đá view Patong.',
    '/uploads/restaurants/baanrimpa-phuket.jpg',
    'Kalim Beach, Phuket',
    'Phuket',
    'Thái Lan',
    'Thái Lan',
    '500-1500 THB',
    4.9,
    1,
    '["wifi", "romantic", "reservation", "cliff-view"]',
    16,
    NOW(),
    NOW()
  ),
  (
    23,
    'Jay Fai Bangkok',
    'jay-fai-bangkok',
    'Nhà hàng Michelin Star với pad kee mao hải sản nổi tiếng.',
    '/uploads/restaurants/jayfai-bangkok.jpg',
    'Phra Nakhon, Bangkok',
    'Bangkok',
    'Thái Lan',
    'Thái Lan',
    '800-1500 THB',
    4.8,
    1,
    '["michelin", "famous", "reservation-required"]',
    17,
    NOW(),
    NOW()
  ),
  (
    24,
    'Thip Samai Pad Thai Bangkok',
    'thipsamai-bangkok',
    'Pad Thai nổi tiếng nhất Bangkok từ năm 1966.',
    '/uploads/restaurants/thipsamai-bangkok.jpg',
    'Phra Nakhon, Bangkok',
    'Bangkok',
    'Thái Lan',
    'Thái Lan',
    '100-300 THB',
    4.7,
    1,
    '["famous", "heritage", "street-food"]',
    17,
    NOW(),
    NOW()
  ),
  (
    25,
    'Locavore Bali',
    'locavore-bali',
    'Nhà hàng fine dining với nguyên liệu địa phương, nhiều giải thưởng.',
    '/uploads/restaurants/locavore-bali.jpg',
    'Ubud, Bali',
    'Bali',
    'Indonesia',
    'Modern',
    '1,000,000-2,000,000 IDR',
    4.9,
    1,
    '["wifi", "fine-dining", "reservation-required", "awards"]',
    18,
    NOW(),
    NOW()
  ),
  (
    26,
    'Warung Ibu Oka Bali',
    'warung-ibu-oka-bali',
    'Babi guling (heo quay) nổi tiếng Bali, Obama đã ghé thăm.',
    '/uploads/restaurants/ibuoka-bali.jpg',
    'Ubud, Bali',
    'Bali',
    'Indonesia',
    'Indonesia',
    '50,000-150,000 IDR',
    4.7,
    1,
    '["famous", "local-specialty", "heritage"]',
    18,
    NOW(),
    NOW()
  ),
  (
    27,
    'Odette Singapore',
    'odette-singapore',
    'Nhà hàng 3 Michelin Stars với ẩm thực Pháp hiện đại.',
    '/uploads/restaurants/odette-singapore.jpg',
    'National Gallery, Singapore',
    'Singapore',
    'Singapore',
    'French',
    'S$200-400',
    4.9,
    1,
    '["michelin-3-star", "fine-dining", "reservation-required"]',
    19,
    NOW(),
    NOW()
  ),
  (
    28,
    'Newton Food Centre Singapore',
    'newton-food-centre',
    'Hawker center nổi tiếng với chilli crab và satay.',
    '/uploads/restaurants/newton-singapore.jpg',
    'Newton Circus, Singapore',
    'Singapore',
    'Singapore',
    'Đa dạng',
    'S$10-30',
    4.5,
    0,
    '["hawker", "local-food", "affordable"]',
    19,
    NOW(),
    NOW()
  ),
  (
    29,
    'Sukiyabashi Jiro Tokyo',
    'sukiyabashi-jiro-tokyo',
    'Nhà hàng sushi 3 Michelin Stars của chef Jiro Ono.',
    '/uploads/restaurants/jiro-tokyo.jpg',
    'Ginza, Tokyo',
    'Tokyo',
    'Nhật Bản',
    'Nhật Bản',
    '¥40,000-60,000',
    5.0,
    1,
    '["michelin-3-star", "reservation-required", "sushi-master"]',
    21,
    NOW(),
    NOW()
  ),
  (
    30,
    'Ichiran Ramen Tokyo',
    'ichiran-ramen-tokyo',
    'Chuỗi ramen nổi tiếng với booth riêng tư.',
    '/uploads/restaurants/ichiran-tokyo.jpg',
    'Shibuya, Tokyo',
    'Tokyo',
    'Nhật Bản',
    'Nhật Bản',
    '¥980-1,500',
    4.6,
    1,
    '["ramen", "private-booth", "famous"]',
    21,
    NOW(),
    NOW()
  ),
  (
    31,
    'Mingles Seoul',
    'mingles-seoul',
    'Nhà hàng 2 Michelin Stars với fusion Hàn Quốc hiện đại.',
    '/uploads/restaurants/mingles-seoul.jpg',
    'Gangnam, Seoul',
    'Seoul',
    'Hàn Quốc',
    'Hàn Quốc',
    '₩100,000-200,000',
    4.8,
    1,
    '["michelin-2-star", "fine-dining", "reservation"]',
    23,
    NOW(),
    NOW()
  ),
  (
    32,
    'Gwangjang Market Seoul',
    'gwangjang-market-seoul',
    'Chợ ẩm thực truyền thống với bindaetteok và mayak gimbap.',
    '/uploads/restaurants/gwangjang-seoul.jpg',
    'Jongno, Seoul',
    'Seoul',
    'Hàn Quốc',
    'Hàn Quốc',
    '₩5,000-20,000',
    4.7,
    1,
    '["market", "street-food", "local-favorite"]',
    23,
    NOW(),
    NOW()
  ),
  (
    33,
    'L''Ambroisie Paris',
    'lambroisie-paris',
    'Nhà hàng 3 Michelin Stars trên Place des Vosges.',
    '/uploads/restaurants/lambroisie-paris.jpg',
    'Le Marais, Paris',
    'Paris',
    'Pháp',
    'French',
    '€250-450',
    4.9,
    1,
    '["michelin-3-star", "fine-dining", "reservation-required"]',
    29,
    NOW(),
    NOW()
  ),
  (
    34,
    'Dishoom London',
    'dishoom-london',
    'Nhà hàng Ấn Độ phong cách Bombay cafe.',
    '/uploads/restaurants/dishoom-london.jpg',
    'Covent Garden, London',
    'London',
    'Anh',
    'Indian',
    '£20-40',
    4.7,
    1,
    '["wifi", "reservation", "trendy"]',
    30,
    NOW(),
    NOW()
  ),
  (
    35,
    'La Pergola Rome',
    'la-pergola-rome',
    'Nhà hàng 3 Michelin Stars duy nhất tại Rome, view toàn cảnh thành phố.',
    '/uploads/restaurants/lapergola-rome.jpg',
    'Monte Mario, Rome',
    'Rome',
    'Ý',
    'Italian',
    '€200-400',
    4.9,
    1,
    '["michelin-3-star", "fine-dining", "city-view", "reservation-required"]',
    31,
    NOW(),
    NOW()
  ) ON DUPLICATE KEY
UPDATE `name` =
VALUES
  (`name`),
  `description` =
VALUES
  (`description`),
  `image` =
VALUES
  (`image`),
  `cuisine` =
VALUES
  (`cuisine`),
  `priceRange` =
VALUES
  (`priceRange`),
  `rating` =
VALUES
  (`rating`),
  `featured` =
VALUES
  (`featured`);

-- ============================================
-- HOÀN TẤT - Thống kê
-- ============================================
SELECT
  '✅ Extended data inserted successfully!' AS status;

SELECT
  (
    SELECT
      COUNT(*)
    FROM
      Destination
  ) as total_destinations,
  (
    SELECT
      COUNT(*)
    FROM
      Tour
  ) as total_tours,
  (
    SELECT
      COUNT(*)
    FROM
      Hotel
  ) as total_hotels,
  (
    SELECT
      COUNT(*)
    FROM
      Restaurant
  ) as total_restaurants;